account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from account.views import registration_view, account_view
from . import views

app_name = 'account'

urlpatterns = [
    path('', account_view, name='account'),
    path('login/', views.user_login, name='login'),
    path('logout/', LogoutView.as_view(next_page='account:login'), name='logout'),
    path('registration/', registration_view, name='registration'),
]

rest/urls.py
from django.urls import path
from rest.views import api_products, api_product_detail, api_brand_detail, api_brands, \
    APIProducts, APIBrands, APIProductDetail

app_name = 'rest'

urlpatterns = [
    # path('api/products/test/', test_api_products),

    # path('products/<int:pk>/', api_product_detail),
    path('products/<int:pk>/', APIProductDetail.as_view()),
    # path('products/', api_products),
    path('products/', APIProducts.as_view()),
    path('brands/<int:pk>/', api_brand_detail),
    # path('brands/', api_brands),
    path('brands/', APIBrands.as_view()),
]

shop/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from . import views
from shop.views import (base_view,
                        product_view,
                        category_view,
                        cart_view,
                        add_to_cart_view,
                        remove_from_cart_view,
                        change_item_qty,
                        make_order_view,
                        search_results_view,
                        order_create_view,
                        contact_view,
                        about_view,
    # account_view,
    # login_view,
                        ListProductView,)
# from account.views import account_view

app_name = 'shop'

urlpatterns = [
    path(r'', base_view, name='base'),
    path("filter/", views.FilterBrandView.as_view(), name='filter'),
    path('category/<slug:category_slug>', category_view, name='category_detail'),
    path('product/<slug:product_slug>', product_view, name='product_detail'),
    path('add_to_cart/<slug:product_slug>', add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/<slug:product_slug>', remove_from_cart_view, name='remove_from_cart'),
    path('change_item_qty', change_item_qty, name='change_item_qty'),
    path('confirmation/', TemplateView.as_view(template_name='shop/confirmation.html'), name='confirmation'),
    path('order/', order_create_view, name='create_order'),
    path('make_order/', make_order_view, name='make_order'),
    path('search_results/', search_results_view, name='search_results'),
    path('cart/', cart_view, name='cart'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    # path('account/', account_view, name='account'),
    # path('registration/', registration_view, name='registration'),
    # path('login/', login_view, name='login'),
    # path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('products/', ListProductView.as_view(), name="product-all"),
    # path('api/products/test/', test_api_products),
    # path('api/products/<int:pk>/', api_product_detail),
    # path('api/products/', api_products),
    # path('api/brands/<int:pk>/', api_brand_detail),
    # path('api/brands/', api_brands),
]

tennis_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import rest.urls
import shop.urls
import account.urls
from tennis_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(account.urls, namespace='account')),
    path('', include(shop.urls, namespace='shop')),
    path('api/', include(rest.urls, namespace='rest')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        {% block title%}Большой теннис{% endblock %}

 		<!-- Google font -->
 		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

 		<!-- Bootstrap -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

 		<!-- Slick -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

 		<!-- nouislider -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

 		<!-- Font Awesome Icon -->
 		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>

 		<!-- Custom stlylesheet -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

 		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
 		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
 		<!--[if lt IE 9]>
 		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
 		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
 		<![endif]-->

        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="{% url 'shop:contact' %}"><i class="fa fa-phone"></i> +7 (999) 765-43-21</a></li>
						<li><a href="{% url 'shop:contact' %}"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
						<li><a href="{% url 'shop:contact' %}"><i class="fa fa-map-marker"></i> г. Москва, ул. Первого Мая, д.16</a></li>
                    </ul>
                    <ul class="header-links pull-right">
                        <li>
                            {% if not request.user.is_authenticated %}
                                <a href="{% url 'account:login' %}"><i class="fa fa-user-o"></i>Гость</a>
                                <a href="{% url 'account:registration' %}"><i></i>Регистрация</a>
                            {% else %}
                                <a href="{% url 'account:account' %}"><i class="fa fa-user-o"></i>{{ request.user }}</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
            <!-- /TOP HEADER -->

            <!-- MAIN HEADER -->
            <div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="{% url 'shop:base' %}" class="logo">
									<img src="{% static 'img/logo.png' %}" alt="">
								</a>
							</div>
						</div>
                        <!-- /LOGO -->

                        <!-- SEARCH BAR -->
                        <div class="col-md-6">
                            <div class="header-search">
                                <form action='{% url "shop:search_results" %}' method="POST">
                                {% csrf_token %}
                                    <select class="input-select">
                                        <option value="0">Все разделы</option>
                                        {% for category in category_list %}
                                            <option value="{{ category.slug }}" name="test">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <input class="input" name="test" placeholder="Поиск">
                                    <button class="search-btn">Искать</button>
                                </form>
                            </div>
                        </div>

{#                        <div class="col-md-6">#}
{##}
{#                            <div class="header-search">#}
{#                                <form action='{% url "shop:search_results" %}' method="POST">#}
{#                                    {% csrf_token %}#}
{#                                    <select class="input-select">#}
{#                                        <option value="0">Все разделы</option>#}
{#                                        {% for category in category_list %}#}
{#                                            <option value="{{ category.slug }}" name="test">{{ category.name }}</option>#}
                                            {#                                            <input type="text" name="test" value="{{ category.slug }}" />#}
{#                                            <input type="text" name="test">#}
{#                                        {% endfor %}#}
{#                                    </select>#}
{#                                    <input class="input" name="test" placeholder="Поиск">#}
{#                                    <button class="search-btn">Искать</button>#}
{#                                </form>#}
{#                            </div>#}
{##}
{#                        </div>#}

                        <!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
								<!-- Cart -->
								<div>
									<a href="{% url 'shop:cart' %}">
										<i class="fa fa-shopping-cart"></i>
										<span>Корзина</span>
                                        <div class="qty">{{ cart.item.count }}</div>
									</a>
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="../">Главная</a></li>
                        {% for category in category_list %}
                            <li><a href="/category/{{ category.slug }}">{{ category.name }}</a></li>
                        {% endfor %}
						<li><a href="{% url 'shop:contact' %}">Контакты</a></li>
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

		<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
{#						<h3 class="breadcrumb-header">Regular Page</h3>#}
						<ul class="breadcrumb-tree">
							<li><a href="{% url 'shop:base' %}">Главная</a></li>
                            {% block breadcrumb %}{% endblock %}
{#							<li class="active">Blank</li>#}
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
                <div>{% block main %}Main{% endblock %}</div>
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Хотите получать информацию о наших скидках и акциях</p>
							<form>
								<input class="input" type="email" placeholder="Введите Ваш Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Подписаться</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="https://twitter.com/"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="https://www.pinterest.ru/"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
        </div>
        <!-- /NEWSLETTER -->

            <!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-lg-5 col-xs-6">
							<div class="footer">
								<h3 class="footer-title"> О Нас</h3>
								<p>Наш магазин предлагает все необходимое <br/> для занятий большим теннисом.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>г. Москва, ул. Первого Мая, д.16</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+7 (999) 765-43-21</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

                        <div class="col-lg-4 col-xs-6">
                            <div class="footer">
                                <h3 class="footer-title">Категории</h3>
                                <ul class="footer-links">
                                    {% for category in category_list %}
                                        <li><a href="/category/{{ category.slug }}">{{ category.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Информация</h3>
								<ul class="footer-links">
									<li><a href="/">Главная</a></li>
									<li><a href="{% url 'shop:contact' %}">Контакты</a></li>
									<li><a href="{% url 'shop:cart' %}">Корзина</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
            <!-- /top footer -->
        </footer>
        <!-- /FOOTER -->

        <!-- jQuery Plugins -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/slick.min.js' %}"></script>
        <script src="{% static 'js/nouislider.min.js' %}"></script>
        <script src="{% static 'js/jquery.zoom.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/base_old.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}My title{% endblock %}</title>
</head>
<body>
<h1><a href="{% url 'shop:base' %}">Home</a></h1>
<div>{% block main %}Main{% endblock %}</div>
<div>{% block sidebar %}Sidebar{% endblock %}</div>
<div>{% block footer %}
    <div>
        {% if not request.get_full_path == '/' %}   {# проверка на главную страницу #}
            <h3>Это не главная страница</h3>
        {% else %}
            <h3>Это главная страница</h3>
        {% endif %}
    </div>
{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>