account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from account.views import registration_view, account_view
from . import views

app_name = 'account'

urlpatterns = [
    path('', account_view, name='account'),
    path('login/', views.user_login, name='login'),
    path('logout/', LogoutView.as_view(next_page='account:login'), name='logout'),
    path('registration/', registration_view, name='registration'),
]

rest/urls.py
from django.urls import path
from rest.views import api_products, api_product_detail, api_brand_detail, api_brands, \
    APIProducts, APIBrands, APIProductDetail

app_name = 'rest'

urlpatterns = [
    # path('api/products/test/', test_api_products),

    # path('products/<int:pk>/', api_product_detail),
    path('products/<int:pk>/', APIProductDetail.as_view()),
    # path('products/', api_products),
    path('products/', APIProducts.as_view()),
    path('brands/<int:pk>/', api_brand_detail),
    # path('brands/', api_brands),
    path('brands/', APIBrands.as_view()),
]

shop/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from . import views
from shop.views import (base_view,
                        product_view,
                        category_view,
                        cart_view,
                        add_to_cart_view,
                        remove_from_cart_view,
                        change_item_qty,
                        make_order_view,
                        search_results_view,
                        order_create_view,
                        contact_view,
                        about_view,
    # account_view,
    # login_view,
                        ListProductView,)
# from account.views import account_view

app_name = 'shop'

urlpatterns = [
    path(r'', base_view, name='base'),
    path("filter/", views.FilterBrandView.as_view(), name='filter'),
    path('category/<slug:category_slug>', category_view, name='category_detail'),
    path('product/<slug:product_slug>', product_view, name='product_detail'),
    path('add_to_cart/<slug:product_slug>', add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/<slug:product_slug>', remove_from_cart_view, name='remove_from_cart'),
    path('change_item_qty', change_item_qty, name='change_item_qty'),
    path('confirmation/', TemplateView.as_view(template_name='shop/confirmation.html'), name='confirmation'),
    path('order/', order_create_view, name='create_order'),
    path('make_order/', make_order_view, name='make_order'),
    path('search_results/', search_results_view, name='search_results'),
    path('cart/', cart_view, name='cart'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    # path('account/', account_view, name='account'),
    # path('registration/', registration_view, name='registration'),
    # path('login/', login_view, name='login'),
    # path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('products/', ListProductView.as_view(), name="product-all"),
    # path('api/products/test/', test_api_products),
    # path('api/products/<int:pk>/', api_product_detail),
    # path('api/products/', api_products),
    # path('api/brands/<int:pk>/', api_brand_detail),
    # path('api/brands/', api_brands),
]

tennis_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import rest.urls
import shop.urls
import account.urls
from tennis_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(account.urls, namespace='account')),
    path('', include(shop.urls, namespace='shop')),
    path('api/', include(rest.urls, namespace='rest')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

shop/models.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return f'{instance.slug}/{filename}'


class Category(models.Model):
    name = models.CharField(max_length=64)
    image = models.ImageField(upload_to=image_folder)
    available = models.BooleanField(default=True, blank=True)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return reverse('shop:category_detail', args=self.slug)
        return reverse('shop:category_detail', kwargs={'category_slug': self.slug})


class Brand(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=128)
    slug = models.SlugField(unique=True, default='')
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.PositiveIntegerField(blank=True, default=0)
    # size = models.IntegerField(max_length=2, blank=True, default=0)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('product_detail', kwargs={'product_slug': self.slug})


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return f'Cart item for product {self.product.title}'


class Cart(models.Model):
    item = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product_slug, qty=1):
        cart = self
        product = Product.objects.get(slug=product_slug)
        cart_item, _ = CartItem.objects.filter(cart__item__cart=cart).get_or_create(product=product)
        if cart_item not in cart.item.all():
            cart_item.qty = int(qty)
            cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
            cart_item.save()
            cart.item.add(cart_item)
            cart.save()
        else:
            cart_item.qty += int(qty)
            cart_item.item_total += int(qty) * Decimal(cart_item.product.price)
            cart_item.save()
            new_cart_total = 0.00
            for item in cart.item.all():
                new_cart_total += float(item.item_total)
            cart.cart_total = new_cart_total
            cart.save()

    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.item.all():
            if cart_item.product == product:
                cart.item.remove(cart_item)
                cart.save()

    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.item.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()


ORDER_STATUS_CHOICES = (
    ('Принят в обработку', 'Принят в обработку'),
    ('Выполняется', 'Выполняется'),
    ('Оплачен', 'Оплачен')
)

BUYING_TYPE_CHOICES = (
    ('Самовывоз', 'Самовывоз'),
    ('Доставка', 'Доставка')
)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ForeignKey(Cart, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.CharField(max_length=64)
    phone = models.CharField(max_length=12)
    address = models.CharField(max_length=256)
    buying_type = models.CharField(max_length=16, choices=BUYING_TYPE_CHOICES, default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=32, choices=ORDER_STATUS_CHOICES)
    comments = models.TextField()

    def __str__(self):
        return f'Заказ №{str(self.id)}'


class Email(models.Model):
    address = models.EmailField(max_length=128, unique=True)

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.utils import timezone

from shop.models import Email


class OrderForm(forms.Form):
    name = forms.CharField(label='Имя')
    last_name = forms.CharField(required=False, label='Фамилия')
    email = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    buying_type = forms.ChoiceField(widget=forms.Select(), required=False, choices=([("self", "Самовывоз"), ("delivery", "Доставка")]))
    date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now(), required=False)
    address = forms.CharField(required=False)
    comments = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['phone'].label = 'Телефон'
        self.fields['phone'].help_text = 'Номер телефона в формате +79011234567'
        self.fields['address'].label = 'Адрес доставки'
        self.fields['address'].help_text = '*Обязательно указывайте город'
        self.fields['date'].label = 'Дата доставки'
        self.fields['date'].help_text = 'Доставка осуществляется на следующий день после оформления заказа'


class EmailForm(ModelForm):
    class Meta:
        model = Email
        fields = ['address']

shop/views.py
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.generic import ListView


from shop.models import Category, Product, Cart, CartItem, Order, Brand
from django.urls import reverse
from shop.forms import OrderForm
from rest_framework import generics, status
from .serializer import ProductSerializer, BrandSerializer


class FilterBrand:
    def get_brand(self):
        return Product.objects.all().values("brand")


def check_cart(request):
    cart_id = request.session.get('cart_id')
    if cart_id is not None:
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    else:
        cart = Cart()
        cart.save()
        request.session['cart_id'] = cart.id
    return cart


def base_view(request):
    new_products = Product.objects.filter(available=True)[0:3]
    best_products = Product.objects.filter(price__gte=3000)[0:3]
    cart = check_cart(request)
    context = {
        'new_products': new_products,
        'best_products': best_products,
        'cart': cart
    }
    return render(request, 'shop/index.html', context)


def contact_view(request):
    products = Product.objects.all().filter(available=True)
    cart = check_cart(request)
    context = {
        'products': products,
        'cart': cart
    }
    return render(request, 'shop/contact.html', context)


def about_view(request):
    products = Product.objects.all().filter(available=True)
    cart = check_cart(request)
    context = {
        'products': products,
        'cart': cart
    }
    return render(request, 'shop/about.html', context)


@login_required
def product_view(request, product_slug):
    cart = check_cart(request)
    product = Product.objects.get(slug=product_slug)
    context = {
        'product': product,
        'cart': cart,
    }
    return render(request, 'shop/product.html', context)


def category_view(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    if request.method == "POST":
        # products = Product.objects.filter(category=category).filter(brand=request.POST.get("brand"))
        products = Product.objects.filter(category=category).filter(brand__in=request.POST.getlist("brand"))
    else:
        products = Product.objects.filter(category=category)
    brands = Brand.objects.all()
    categories = Category.objects.filter(available=True)
    cart = check_cart(request)
    paginator = Paginator(products, 4)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    pages = paginator.get_page(page_num)

    context = {
        'category': category,
        'products': products,
        'brands': brands,
        'categories': categories,
        'cart': cart,
        'pages': pages,
    }
    return render(request, 'shop/category.html', context)


def cart_view(request):
    cart = check_cart(request)
    context = {
        'cart': cart,
    }
    return render(request, 'shop/cart.html', context)


def add_to_cart_view(request, product_slug):
    cart = check_cart(request)
    product = Product.objects.get(slug=product_slug)
    if 'qty' in request.POST:
        cart.add_to_cart(product.slug, int(request.POST.get("qty")))
    else:
        cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.item.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return HttpResponseRedirect(reverse('shop:cart'))


def remove_from_cart_view(request, product_slug):
    cart = check_cart(request)
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.item.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return HttpResponseRedirect(reverse('shop:cart'))


def change_item_qty(request):
    cart = check_cart(request)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart_item = CartItem.objects.get(id=int(item_id))
    cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
    cart.change_qty(qty, item_id)
    return JsonResponse({'cart_total': cart.item.count(),
                         'item_total': cart_item.item_total,
                         'cart_total_price': cart.cart_total})


def order_create_view(request):
    cart = check_cart(request)
    form = OrderForm(request.POST or None)
    context = {
        'cart': cart,
        'form': form,
    }
    return render(request, 'shop/order.html', context)


def make_order_view(request):
    cart = check_cart(request)
    form = OrderForm(request.POST or None)
    context = {
        'cart': cart,
        'form': form,
    }
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        email = form.cleaned_data['email']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']
        new_order = Order.objects.create(
            user=request.user,
            items=cart,
            total=cart.cart_total,
            first_name=name,
            last_name=last_name,
            phone=phone,
            email=email,
            address=address,
            buying_type=buying_type,
            comments=comments
        )
        # new_order = Order()
        # new_order.user = request.user
        # # new_order.items.add(cart)
        # new_order.items = cart
        # new_order.first_name = name
        # new_order.last_name = last_name
        # new_order.phone = phone
        # new_order.address = address
        # new_order.buying_type = buying_type
        # new_order.comments = comments
        # new_order.total = cart.cart_total
        # new_order.email = cart.email
        # new_order.save()
        del request.session['cart_id']
        del request.session['total']

        return HttpResponseRedirect(reverse('shop:confirmation'))
    return render(request, 'shop/order.html', context)


def search_results_view(request):
    products = []
    if request.method == "POST":
        products = Product.objects.filter(title__icontains=request.POST.get('test'))
    brands = Brand.objects.all()
    cart = check_cart(request)
    paginator = Paginator(products, 4)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    pages = paginator.get_page(page_num)

    context = {
        'products': products,
        'brands': brands,
        # 'categories': categories,
        'cart': cart,
        'pages': pages,
    }
    return render(request, 'shop/search_results.html', context)


class ListProductView(generics.ListAPIView):
    """
    Providers a get method handler.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class FilterBrandView(FilterBrand, ListView):
    def get_queryset(self):
        queryset = Product.objects.filter(brand__in=self.request.GET.getlist("brand"))
        return queryset

shop/templates/shop/about.html
{% extends 'base.html' %}

{% block title %}
    <title>О Нас</title>
{% endblock %}

{% block cart %}
    <div class="qty">{{ cart.item.count }}</div>
{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url 'shop:about' %}">О Нас</a></li>
{% endblock %}

{% block main %}
    <h2>О Нас</h2>
{% endblock %}

{% block sidebar %}

{% endblock %}

shop/templates/shop/cart.html
{% extends 'base.html' %}

{% block title %}
    <title>Корзина ({{ cart.item.count }} товара в корзине)</title>
{% endblock %}

{% block cart %}
    <div class="qty">{{ cart.item.count }}</div>
{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url 'shop:cart' %}">Корзина</a></li>
{% endblock %}

{% block main %}
{#    <h2>{{ cart }}</h2>#}
    {% if cart.item.count > 0 %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Товар</th>
                <th scope="col">Количество</th>
                <th scope="col">Цена</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart.item.all %}
                <tr>
                    <th scope="row"></th>
                    <td><h4>{{ item.product.title }}</h4></td>
                    <td>
                        <form action="" method="get">
                            <input type="number" name="qty" class="cart-item-qty" data-id="{{ item.id }}" value="{{ item.qty }}" min="1" style="width: 40px">
                        </form>
                    </td>
                    <td><h5 id="cart-item-total-{{ item.id }}">{{ item.item_total }} руб.</h5></td>
                    <td><a href='{% url 'shop:remove_from_cart' product_slug=item.product.slug %}'><button type="button" class="btn btn-danger">Удалить</button></a></td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th></th>
                <th>Итого:</th>
                <th></th>
                <th class="text" id="cart-total-price"><h4>{{ cart.cart_total }} руб.</h4></th>
                <th></th>
            </tr>
            </tfoot>
        </table>
        <a href='{% url 'shop:create_order' %}'><button type="button" class="btn btn-success">Сделать заказ</button></a>
    {% else %}
        <h3>Ваша корзина пуста</h3>
    {% endif %}

    <br>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.cart-item-qty').on('click', function () {
                qty = $(this).val()
                item_id = $(this).attr('data-id')
                data = {
                    qty: qty,
                    item_id: item_id
                }
                $.ajax({
                    type: "GET",
                    url: '{% url 'shop:change_item_qty' %}',
                    data: data,
                    success: function(data){
                        $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + ' руб.')
                        $('#cart-total-price').html(parseFloat(data.cart_total_price).toFixed(2) + ' руб.')
                    }
                })
            })
        })

    </script>

    {#    <script src="{% static 'component/js/component.js' %}"></script>#}
{% endblock %}

{% block sidebar %}

{% endblock %}

shop/templates/shop/order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% endblock %}

{% block cart %}
    <div class="qty">{{ cart.item.count }}</div>
{% endblock %}

{% block breadcrumb %}
    <li><a href="#">Заказ</a></li>
{% endblock %}

{% block main %}

    <form action='{% url "shop:make_order" %}' method="POST">
    {% csrf_token %}
    <div class="section">
        <div class="container">
            <div class="row">

                <div class="col-md-7">
                    <!-- Billing Details -->
                    <div class="billing-details">
                        <div class="section-title">
                            <h3 class="title">Параметры доставки</h3>
                        </div>

                        <div class="form-group">
                            <label for="name">Имя</label>
                            <input type="text" name="name" required id="id_name" class="form-control" placeholder="{{ form.name.label }}">
                        </div>
                        <div class="form-group">
                            <label for="last_name">Фамилия</label>
                            <input type="text" name="last_name" id="id_last_name" class="form-control" placeholder="{{ form.last_name.label }}">
                        </div>
                        <div class="form-group">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" required id="id_phone" class="form-control" placeholder="{{ form.phone.label }}">
                            <span class="helptext">Номер телефона в формате +79011234567</span>
                        </div>
                        <div class="form-group">
                            <label for="email">Электронная почта</label>
                            <input type="text" name="email" required id="id_email" class="form-control" placeholder="{{ form.email.label }}">
                        </div>
                        <div class="form-group">
                            <label for="date">Дата доставки</label>
                            <input type="date" name="date" id="id_date" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="buying_type">Способ доставки </label>
                            <select class="custom-select mr-sm-2" name="buying_type" id="id_buying_type">
                                <option selected>...</option>
                                <option value="self">Самовывоз</option>
                                <option value="delivery">Доставка</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="address">Адрес доставки</label>
                            <input type="text" name="address" id="id_address" class="form-control" placeholder="{{ form.address.label }}">
                            <span class="help text">{{ form.address.help_text }}</span>
                        </div>
                        <div class="order-notes">
                            <label for="OrderNotes">Комментарий к заказу</label>
                            <textarea class="input" name="comments" id="id_comments" placeholder="Укажите подробности доставки"></textarea>
                        </div>
                    </div>
                    <!-- /Billing Details -->
                </div>

                <!-- Order Details -->
                <div class="col-md-5 order-details">
                    <div class="section-title text-center">
                        <h3 class="title">Ваш заказ</h3>
                    </div>
                    <div class="order-summary">
                        <div class="order-col">
                            <div><strong>Товар</strong></div>
                            <div><strong>Цена</strong></div>
                        </div>
                        <div class="order-products">
                            {% for item in cart.item.all %}

                                <div class="order-col">
                                    <div>{{ item.qty }}x {{ item.product.title }}</div>
                                    <div>{{ item.item_total }}</div>
                                </div>

                            {% endfor %}

                        </div>
                        <div class="order-col">
                            <div>Доставка</div>
                            <div><strong>Бесплатно</strong></div>
                        </div>
                        <div class="order-col">
                            <div><strong>Всего (руб.)</strong></div>
                            <div><strong class="order-total">{{ cart.cart_total }}</strong></div>
                        </div>
                    </div>
                    <div class="payment-method">
                        <div class="input-radio">
                            <input type="radio" name="payment" id="payment-1">
                            <label for="payment-1">
                                <span></span>
                                Оплата наличными курьеру
                            </label>
                            <div class="caption">
                                <p>Заказ можно полатить наличными курьеру в момент получения.</p>
                            </div>
                        </div>
                        <div class="input-radio">
                            <input type="radio" name="payment" id="payment-2">
                            <label for="payment-2">
                                <span></span>
                                Оплата картой курьеру
                            </label>
                            <div class="caption">
                                <p>Заказ можно полатить банковской картой курьеру в момент получения.</p>
                            </div>
                        </div>
                        <div class="input-radio">
                            <input type="radio" name="payment" id="payment-3">
                            <label for="payment-3">
                                <span></span>
                                Безналичная оплата
                            </label>
                            <div class="caption">
                                <p>Заказ можно оплатить банковским переводом. В момент подтверждения заказа менеджер расскажет все подробности.</p>
                            </div>
                        </div>
                    </div>
                    <div class="input-checkbox">
                        <input type="checkbox" id="terms">
                        <label for="terms">
                            <span></span>
                            Я подтверждаю правильность заказа и выбранный способ оплаты
                        </label>
                    </div>
                    <input type='submit' class='primary-btn order-submit' value='Оформить заказ'>
                </div>
                <!-- /Order Details -->
            </div>
        </div>
    </div>
    </form>

    <script>
        <!--
        function btnClick(a)
        {
            alert('hello' + a.value)
            {#var Txt1 = "";#}
            {#var Txt2 = "";#}
            {#Txt1 = document.Test.bt.value;#}
            {#Txt2 = document.Test.bt.name;#}
            {#document.getElementById('ex1').innerHTML="<HR>"+#}
            {#    "Вы нажали кнопку: " + Txt1.bold() +#}
            {#    " с именем: "  + Txt2.bold() +"<HR>";#}
        }
        //-->
    </script>

{% endblock %}

{% block sidebar %}
{% endblock %}

shop/templates/shop/search_results.html
{% extends 'base.html' %}
{% load products_tag %}

{% block title %}
    <title>Результаты поиска</title>
{% endblock %}

{% block main %}
{#    <h2>{{ category.name }}</h2>#}
    <div class="section">
        <!-- container -->
        <div class="container">
            <div class="row">
                {% if products.all.count == 0 %}
                    <div><h3>Поиск не дал результата</h3></div>
                {% else %}
                    <div id="store" class="col-md-9">
                        <div class="row">
                            <!-- product -->
                            {% for page in pages %}
                                <div class="col-md-4 col-xs-6">
                                    <div class="product">

                                        <div class="product-img">
                                            <img src="{{ page.image.url }}" alt="">
                                        </div>
                                        <div class="product-body">
                                            <p class="product-category">{{ page.brand.name }}</p>
                                            <h3 class="product-name"><a href="{% url 'shop:product_detail' page.slug %}">{{ page.title }}</a></h3>
                                            <h4 class="product-price">{{ page.price }} руб.</h4>
                                        </div>
                                        <div class="add-to-cart">
                                            <a href="{% url 'shop:add_to_cart' product_slug=page.slug %}"><button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> купить</button></a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="clearfix visible-sm visible-xs"></div>
                        </div>
                    </div>
                    <div class="store-filter clearfix">
                        <span class="store-qty">На текущей старнице {{ pages.object_list|length }} из {{ pages.paginator.count }} товаров</span>
                        <ul class="store-pagination">
                            {% for count in  pages.paginator.page_range %}
                                <li><a href="?page={{ count }}">{{ count }}</a></li>
                            {% endfor %}
                            {% if pages.has_next %}
                                <li><a href="?page={{ pages.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block sidebar %}

{% endblock %}